package chartcreator;


import observer.Observer;
import subject.Subject;
import subject.Stock;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shobhit
 */
public class ChartFrame extends javax.swing.JFrame implements Runnable, Observer {

    private ChartCreator chartCreator;
    private List<Integer> currentPrice;
    private List<Integer> openingPrice;
    private List<Integer> closingPrice;
    private List<Integer> askPrice;
    private List<Integer> bidPrice;
    private List<Integer> volumePrice;
    private List<Integer> tenDayVolumePrice;
    private List<Integer> currentPoints;
    
    public ChartFrame(ChartCreator chartCreator){
        initComponents();
        this.chartCreator = chartCreator;
        currentPrice = new ArrayList<Integer>();
        openingPrice = new ArrayList<Integer>();
        closingPrice = new ArrayList<Integer>();
        askPrice = new ArrayList<Integer>();
        bidPrice = new ArrayList<Integer>();
        volumePrice = new ArrayList<Integer>();
        tenDayVolumePrice = new ArrayList<Integer>();
        currentPoints = currentPrice;
        chartJPanel.setLayout(new BorderLayout());
        setVisible(true);
        setResizable(false);
    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartJPanel = new javax.swing.JPanel();
        priceOptionComboBox = new javax.swing.JComboBox();
        numberOfPointsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chartJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chartJPanelLayout = new javax.swing.GroupLayout(chartJPanel);
        chartJPanel.setLayout(chartJPanelLayout);
        chartJPanelLayout.setHorizontalGroup(
            chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartJPanelLayout.setVerticalGroup(
            chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        priceOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Current Price","Opening Price", "Closing Price", "Ask Price", "Bid Price", "Volume Price", "Ten Day Volume"}));

        jLabel1.setText("Number of update");

        jLabel2.setText("Currently showing");

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfPointsTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showButton, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfPointsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(showButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        
        int index = priceOptionComboBox.getSelectedIndex();
        if(index == 0){
            currentPoints = currentPrice;
        }
        
        if(index == 1){
            currentPoints = openingPrice;
        }
        
        if(index == 2){
            currentPoints = closingPrice;
        }
        
        if(index == 3){
            currentPoints = askPrice;
        }
        
        if(index == 4){
            currentPoints = bidPrice;
        }
        
        if(index == 5){
            currentPoints = volumePrice;
        }
        
        if(index == 6){
            currentPoints = tenDayVolumePrice;
        }
    }//GEN-LAST:event_showButtonActionPerformed

    public void showChart(){
        if(currentPrice.size() == 0) return;
        
        JFreeChart chart = chartCreator.createChart(currentPoints);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartJPanel.removeAll();
        chartJPanel.updateUI();
        chartJPanel.add(BorderLayout.CENTER, chartPanel); 
        chartJPanel.repaint();
        chartJPanel.revalidate();
    }

    @Override
    public void update(Subject subject) {
        Stock stock = (Stock)subject;
        currentPrice.add(stock.getCurrentPrice());
        openingPrice.add(stock.getOpeningPrice());
        closingPrice.add(stock.getClosingPrice());
        bidPrice.add(stock.getBidPrice());
        askPrice.add(stock.getAskPrice());
        volumePrice.add(stock.getCurrentVolume());
        tenDayVolumePrice.add(stock.getTenDayVolume());
    }

    @Override
    public void run() {
        while(true){
            try {
                showChart();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(ChartFrame.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numberOfPointsTextField;
    private javax.swing.JComboBox priceOptionComboBox;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
}
