
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shobhit
 */
public class StockMonitoringSystemInterface extends javax.swing.JFrame {

    private DefaultListModel<String> listModel = new DefaultListModel<>();
    private Map<Integer, JTable> selectedIndexToTable;
    /**
     * Creates new form StockMonitoringSytemInterface
     */
    public StockMonitoringSystemInterface() {
        initComponents();
        InitializeIntegerToTableMapping();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableStocksJList = new javax.swing.JList();
        windowOneJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        windowOne = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        windowTwo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        windowThree = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        windowFour = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        windowFive = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        windowSix = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        showStockButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        windowComboBox = new javax.swing.JComboBox();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        availableStocksJList.setModel(listModel);
        jScrollPane1.setViewportView(availableStocksJList);

        javax.swing.GroupLayout windowOneJPanelLayout = new javax.swing.GroupLayout(windowOneJPanel);
        windowOneJPanel.setLayout(windowOneJPanelLayout);
        windowOneJPanelLayout.setHorizontalGroup(
            windowOneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        windowOneJPanelLayout.setVerticalGroup(
            windowOneJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        windowOne.setModel(new DefaultTableModelObserver());
        windowOne.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(windowOne);

        windowTwo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        windowTwo.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(windowTwo);

        windowThree.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        windowThree.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(windowThree);

        windowFour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        windowFour.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(windowFour);

        windowFive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        windowFive.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(windowFive);

        windowSix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        windowSix.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(windowSix);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        showStockButton.setText("Show Stocks");
        showStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStockButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Show Selected Stocks in ");

        windowComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Window 1", "Window 2", "Window 3", "Window 4", "Window 5", "Window 6" }));
        windowComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                windowComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(windowOneJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(windowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showStockButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(windowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(windowOneJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStockButtonActionPerformed
        new AvailableStock();
        addAllStocks();
    }//GEN-LAST:event_showStockButtonActionPerformed

    private void windowComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_windowComboBoxItemStateChanged
        int index = windowComboBox.getSelectedIndex();
//        Map<String, Stock> stocks = AvailableStock.getAvailableStock();
//        if(index == 0) return;
//        if (evt.getStateChange() == ItemEvent.SELECTED) {
//            JTable window = selectedIndexToTable.get(index);
//            ArrayList <String> selectedJList = (ArrayList <String>) availableStocksJList.getSelectedValuesList(); 
//            for(String s : selectedJList){
//                String stockName = s.split(",")[0];
//                DefaultTableModel model = (DefaultTableModel) window.getModel();
//                DefaultTableModelObserver o = (DefaultTableModelObserver) model;
//                model.addRow(new Object[]{stockName, "Column 2", "Column 3"});
//                stocks.get(s).addObserver(o);
//            }    
//        }
    }//GEN-LAST:event_windowComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockMonitoringSystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockMonitoringSystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockMonitoringSystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockMonitoringSystemInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockMonitoringSystemInterface().setVisible(true);
                
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList availableStocksJList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton showStockButton;
    private javax.swing.JComboBox windowComboBox;
    private javax.swing.JTable windowFive;
    private javax.swing.JTable windowFour;
    private javax.swing.JTable windowOne;
    private javax.swing.JPanel windowOneJPanel;
    private javax.swing.JTable windowSix;
    private javax.swing.JTable windowThree;
    private javax.swing.JTable windowTwo;
    // End of variables declaration//GEN-END:variables

    private void addAllStocks() {
//        Map<String, Stock> allStocks = AvailableStock.getAvailableStock();
//        for(String symbol: allStocks.keySet()){
//            listModel.addElement(symbol + ", " + allStocks.get(symbol).getCompanyName());
//        }
//        
//        availableStocksJList.setModel(listModel);
    }

    private void InitializeIntegerToTableMapping() {
        DefaultTableModel tableModel = new DefaultTableModelObserver();
        tableModel.addColumn("Name");
        tableModel.addColumn("Column 1");
        tableModel.addColumn("Column 2");
        

        windowFour.setModel(tableModel);
        windowOne.setModel(tableModel);
        selectedIndexToTable = new HashMap<>();
        selectedIndexToTable.put(1, windowOne);
        selectedIndexToTable.put(2, windowTwo);
        selectedIndexToTable.put(3, windowThree);
        selectedIndexToTable.put(4, windowFour);
        selectedIndexToTable.put(5, windowFive);
        selectedIndexToTable.put(6, windowSix);  
    }
}
